package org.socialweb.model;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EstadoCiudad generated by hbm2java
 */
@Entity
@Table(name="estado_ciudad"
    ,schema="public"
)
public class EstadoCiudad implements java.io.Serializable {

    private int codigo;
    private String descripcion;
    private List<Ciudad> ciudades = new ArrayList<Ciudad>(0);

    public EstadoCiudad() {}
	
    public EstadoCiudad(int codigo,
            String descripcion) {

        this.codigo = codigo;
        this.descripcion = descripcion;
    }

    public EstadoCiudad(int codigo,
            String descripcion,
            List<Ciudad> ciudades) {

        this.codigo = codigo;
        this.descripcion = descripcion;
        this.ciudades = ciudades;
    }

    @Id
    @JoinColumn(name="codigo",
            referencedColumnName="codigo",
            nullable=false,
            unique=true,
            insertable=false,
            updatable=false)
    public int getCodigo() {
        return this.codigo;
    }

    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    @Column(name="descripcion",
            nullable=false)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @OneToMany(fetch=FetchType.LAZY,
            cascade=CascadeType.ALL,
            mappedBy="estadoCiudad")
    public List<Ciudad> getCiudades() {
        return this.ciudades;
    }

    public void setCiudades(List<Ciudad> ciudades) {
        this.ciudades = ciudades;
    }
}