package org.socialweb.model;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EstadoProvincia generated by hbm2java
 */
@Entity
@Table(name="estado_provincia"
    ,schema="public"
)
public class EstadoProvincia implements java.io.Serializable {

    private int codigo;
    private String descripcion;
    private List<Provincia> provincias = new ArrayList<Provincia>(0);

    public EstadoProvincia() {}

    public EstadoProvincia(int codigo,
            String descripcion) {

        this.codigo = codigo;
        this.descripcion = descripcion;
    }

    public EstadoProvincia(int codigo,
            String descripcion,
            List<Provincia> provincias) {

        this.codigo = codigo;
        this.descripcion = descripcion;
        this.provincias = provincias;
    }

    @Id 
    @Column(name="codigo",
            unique=true,
            nullable=false)
    public int getCodigo() {
        return this.codigo;
    }

    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    @Column(name="descripcion",
            nullable=false)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @OneToMany(fetch=FetchType.LAZY,
            mappedBy="provincias")
    public List<Provincia> getProvincias() {
        return this.provincias;
    }

    public void setProvincias(List<Provincia> provincias) {
        this.provincias = provincias;
    }
}