package org.socialweb.model;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EstadoPersona generated by hbm2java
 */
@Entity
@Table(name="estado_persona"
    ,schema="public"
)
public class EstadoPersona implements java.io.Serializable {

    private int codigo;
    private String descripcion;
    private List<Persona> personas = new ArrayList<Persona>(0);

    public EstadoPersona() {}
	
    public EstadoPersona(int codigo,
            String descripcion) {

        this.codigo = codigo;
        this.descripcion = descripcion;
    }

    public EstadoPersona(int codigo,
            String descripcion,
            List<Persona> personas) {

        this.codigo = codigo;
        this.descripcion = descripcion;
        this.personas = personas;
    }

    @Id
    @Column(name="codigo",
            unique=true,
            nullable=false)
    public int getCodigo() {
        return this.codigo;
    }

    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    @Column(name="descripcion",
            nullable=false)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @OneToMany(fetch=FetchType.LAZY,
            mappedBy="personas")
    public List<Persona> getPersonas() {
        return this.personas;
    }

    public void setPersonas(List<Persona> personas) {
        this.personas = personas;
    }
}