package org.socialweb.model;

import java.util.Date;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pais generated by hbm2java
 */
@Entity
@Table(name="pais"
    ,schema="public"
)
public class Pais implements java.io.Serializable {

    private int codigo;
    private EstadoPais estadoPais;
    private String nombre;
    private String nombreIso;
    private String codigoIsoAlfa2;
    private String codigoIsoAlfa3;
    private int codigoIso;
    private String usrCreate;
    private Date timeCreate;
    private String usrLastUpdate;
    private Date timeLastUpdate;
    private List<Provincia> provincias = new ArrayList<Provincia>(0);

    public Pais() {}
	
    public Pais(int codigo,
            EstadoPais estadoPais,
            String nombre,
            String nombreIso,
            String codigoIsoAlfa2,
            String codigoIsoAlfa3,
            int codigoIso,
            String usrCreate,
            Date timeCreate,
            String usrLastUpdate,
            Date timeLastUpdate) {

        this.codigo = codigo;
        this.estadoPais = estadoPais;
        this.nombre = nombre;
        this.nombreIso = nombreIso;
        this.codigoIsoAlfa2 = codigoIsoAlfa2;
        this.codigoIsoAlfa3 = codigoIsoAlfa3;
        this.codigoIso = codigoIso;
        this.usrCreate = usrCreate;
        this.timeCreate = timeCreate;
        this.usrLastUpdate = usrLastUpdate;
        this.timeLastUpdate = timeLastUpdate;
    }

    public Pais(int codigo,
            EstadoPais estadoPais,
            String nombre,
            String nombreIso,
            String codigoIsoAlfa2,
            String codigoIsoAlfa3,
            int codigoIso,
            String usrCreate,
            Date timeCreate,
            String usrLastUpdate,
            Date timeLastUpdate,
            List<Provincia> provincias) {

        this.codigo = codigo;
        this.estadoPais = estadoPais;
        this.nombre = nombre;
        this.nombreIso = nombreIso;
        this.codigoIsoAlfa2 = codigoIsoAlfa2;
        this.codigoIsoAlfa3 = codigoIsoAlfa3;
        this.codigoIso = codigoIso;
        this.usrCreate = usrCreate;
        this.timeCreate = timeCreate;
        this.usrLastUpdate = usrLastUpdate;
        this.timeLastUpdate = timeLastUpdate;
        this.provincias = provincias;
    }

    @Id
    @SequenceGenerator(name="paisGenerator",
            sequenceName="seq_codigo_pais")
    @GeneratedValue(strategy=GenerationType.SEQUENCE,
            generator="paisGenerator")
    @Column(name="codigo",
            unique=true,
            nullable=false,
            insertable=false,
            updatable=false)
    public int getCodigo() {
        return this.codigo;
    }

    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="estado",
            nullable=false,
            insertable=false,
            updatable=false)
    public EstadoPais getEstadoPais() {
        return this.estadoPais;
    }

    public void setEstadoPais(EstadoPais estadoPais) {
        this.estadoPais = estadoPais;
    }

    @Column(name="nombre",
            nullable=false)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name="nombre_iso",
            nullable=false)
    public String getNombreIso() {
        return this.nombreIso;
    }

    public void setNombreIso(String nombreIso) {
        this.nombreIso = nombreIso;
    }

    @Column(name="codigo_iso_alfa_2",
            nullable=false)
    public String getCodigoIsoAlfa2() {
        return this.codigoIsoAlfa2;
    }

    public void setCodigoIsoAlfa2(String codigoIsoAlfa2) {
        this.codigoIsoAlfa2 = codigoIsoAlfa2;
    }

    @Column(name="codigo_iso_alfa_3",
            nullable=false)
    public String getCodigoIsoAlfa3() {
        return this.codigoIsoAlfa3;
    }

    public void setCodigoIsoAlfa3(String codigoIsoAlfa3) {
        this.codigoIsoAlfa3 = codigoIsoAlfa3;
    }

    @Column(name="codigo_iso",
            nullable=false)
    public int getCodigoIso() {
        return this.codigoIso;
    }

    public void setCodigoIso(int codigoIso) {
        this.codigoIso = codigoIso;
    }

    @Column(name="usr_create",
            nullable=false)
    public String getUsrCreate() {
        return this.usrCreate;
    }

    public void setUsrCreate(String usrCreate) {
        this.usrCreate = usrCreate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="time_create",
            nullable=false,
            length=29)
    public Date getTimeCreate() {
        return this.timeCreate;
    }

    public void setTimeCreate(Date timeCreate) {
        this.timeCreate = timeCreate;
    }

    @Column(name="usr_last_update",
            nullable=false)
    public String getUsrLastUpdate() {
        return this.usrLastUpdate;
    }

    public void setUsrLastUpdate(String usrLastUpdate) {
        this.usrLastUpdate = usrLastUpdate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="time_last_update",
            nullable=false,
            length=29)
    public Date getTimeLastUpdate() {
        return this.timeLastUpdate;
    }

    public void setTimeLastUpdate(Date timeLastUpdate) {
        this.timeLastUpdate = timeLastUpdate;
    }

    @OneToMany(fetch=FetchType.LAZY,
        mappedBy="pais")
    public List<Provincia> getProvincias() {
        return this.provincias;
    }

    public void setProvincias(List<Provincia> provincias) {
        this.provincias = provincias;
    }
}