package org.socialweb.model;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * PersonaJuridica generated by hbm2java
 */
@Entity
@Table(name="persona_juridica"
    ,schema="public"
)
public class PersonaJuridica implements java.io.Serializable {

     private int personaForeign;
     private Persona persona;
     private TipoPersonaJuridica tipoPersonaJuridica;
     private String razonSocial;
     private String nombreComercial;
     private String usrCreate;
     private Date timeCreate;
     private String usrLastUpdate;
     private Date timeLastUpdate;

    public PersonaJuridica() {}

    public PersonaJuridica(Persona persona,
            TipoPersonaJuridica tipoPersonaJuridica,
            String razonSocial,
            String nombreComercial,
            String usrCreate,
            Date timeCreate,
            String usrLastUpdate,
            Date timeLastUpdate) {

        this.persona = persona;
        this.tipoPersonaJuridica = tipoPersonaJuridica;
        this.razonSocial = razonSocial;
        this.nombreComercial = nombreComercial;
        this.usrCreate = usrCreate;
        this.timeCreate = timeCreate;
        this.usrLastUpdate = usrLastUpdate;
        this.timeLastUpdate = timeLastUpdate;
    }

    @GenericGenerator(name="generator",
            strategy="foreign",
            parameters=@Parameter(name="property",
                    value="persona"))
    @Id @GeneratedValue(generator="generator")
    @Column(name="persona", unique=true, nullable=false)
    public int getPersonaForeign() {
        return this.personaForeign;
    }

    public void setPersonaForeign(int personaForeign) {
        this.personaForeign = personaForeign;
    }

    @OneToOne(fetch=FetchType.LAZY)
    @PrimaryKeyJoinColumn
    public Persona getPersona() {
        return this.persona;
    }

    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tipo_persona_juridica",
            nullable=false)
    public TipoPersonaJuridica getTipoPersonaJuridica() {
        return this.tipoPersonaJuridica;
    }

    public void setTipoPersonaJuridica(TipoPersonaJuridica tipoPersonaJuridica) {
        this.tipoPersonaJuridica = tipoPersonaJuridica;
    }

    @Column(name="razon_social",
            nullable=false)
    public String getRazonSocial() {
        return this.razonSocial;
    }

    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }

    @Column(name="nombre_comercial")
    public String getNombreComercial() {
        return this.nombreComercial;
    }

    public void setNombreComercial(String nombreComercial) {
        this.nombreComercial = nombreComercial;
    }

    @Column(name="usr_create",
            nullable=false)
    public String getUsrCreate() {
        return this.usrCreate;
    }

    public void setUsrCreate(String usrCreate) {
        this.usrCreate = usrCreate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="time_create",
            nullable=false,
            length=29)
    public Date getTimeCreate() {
        return this.timeCreate;
    }

    public void setTimeCreate(Date timeCreate) {
        this.timeCreate = timeCreate;
    }

    @Column(name="usr_last_update",
            nullable=false)
    public String getUsrLastUpdate() {
        return this.usrLastUpdate;
    }

    public void setUsrLastUpdate(String usrLastUpdate) {
        this.usrLastUpdate = usrLastUpdate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="time_last_update",
            nullable=false,
            length=29)
    public Date getTimeLastUpdate() {
        return this.timeLastUpdate;
    }

    public void setTimeLastUpdate(Date timeLastUpdate) {
        this.timeLastUpdate = timeLastUpdate;
    }
}