package org.socialweb.model;

import java.io.Serializable;
import java.util.Date;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name="persona"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames="cuit_cuil_cdi") 
)
public class Persona implements java.io.Serializable {

    private int codigo;
    private Domicilio domicilioReal;
    private Domicilio domicilioFiscal;
    private Domicilio domicilioLegal;
    private EstadoPersona estadoPersona;
    private Serializable cuitCuilCdi;
    private String usrCreate;
    private Date timeCreate;
    private String usrLastUpdate;
    private Date timeLastUpdate;
    private PersonaJuridica personaJuridica;
    private PersonaHumana personaHumana;
    private List<Contacto> contactos = new ArrayList<Contacto>(0);

    public Persona() {}

    public Persona(int codigo,
            Domicilio domicilioReal,
            EstadoPersona estadoPersona,
            Serializable cuitCuilCdi,
            String usrCreate,
            Date timeCreate,
            String usrLastUpdate,
            Date timeLastUpdate) {

        this.codigo = codigo;
        this.domicilioReal = domicilioReal;
        this.estadoPersona = estadoPersona;
        this.cuitCuilCdi = cuitCuilCdi;
        this.usrCreate = usrCreate;
        this.timeCreate = timeCreate;
        this.usrLastUpdate = usrLastUpdate;
        this.timeLastUpdate = timeLastUpdate;
    }

    public Persona(int codigo,
            Domicilio domicilioReal,
            Domicilio domicilioFiscal,
            Domicilio domicilioLegal,
            EstadoPersona estadoPersona,
            Serializable cuitCuilCdi,
            String usrCreate,
            Date timeCreate,
            String usrLastUpdate,
            Date timeLastUpdate,
            PersonaJuridica personaJuridica,
            PersonaHumana personaHumana,
            List<Contacto> contactos) {

        this.codigo = codigo;
        this.domicilioReal = domicilioReal;
        this.domicilioFiscal = domicilioFiscal;
        this.domicilioLegal = domicilioLegal;
        this.estadoPersona = estadoPersona;
        this.cuitCuilCdi = cuitCuilCdi;
        this.usrCreate = usrCreate;
        this.timeCreate = timeCreate;
        this.usrLastUpdate = usrLastUpdate;
        this.timeLastUpdate = timeLastUpdate;
        this.personaJuridica = personaJuridica;
        this.personaHumana = personaHumana;
        this.contactos = contactos;
    }

    @Id
    @SequenceGenerator(name="personaGenerator",
            sequenceName="seq_codigo_persona")
    @GeneratedValue(strategy=GenerationType.SEQUENCE,
            generator="personaGenerator")
    @Column(name="codigo",
            unique=true,
            nullable=false)
    public int getCodigo() {
        return this.codigo;
    }

    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="domicilioReal",
            nullable=false,
            insertable=false,
            updatable=false)
    public Domicilio getDomicilioReal() {
        return this.domicilioReal;
    }

    public void setDomicilioReal(Domicilio domicilioReal) {
        this.domicilioReal = domicilioReal;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="domicilioFiscal",
            insertable=false,
            updatable=false)
    public Domicilio getDomicilioFiscal() {
        return this.domicilioFiscal;
    }

    public void setDomicilioFiscal(Domicilio domicilioFiscal) {
        this.domicilioFiscal = domicilioFiscal;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="domicilioLegal",
            insertable=false,
            updatable=false)
    public Domicilio getDomicilioLegal() {
        return this.domicilioLegal;
    }

    public void setDomicilioLegal(Domicilio domicilioLegal) {
        this.domicilioLegal = domicilioLegal;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="estado",
            nullable=false,
            insertable=false,
            updatable=false)
    public EstadoPersona getEstadoPersona() {
        return this.estadoPersona;
    }

    public void setEstadoPersona(EstadoPersona estadoPersona) {
        this.estadoPersona = estadoPersona;
    }

    @Column(name="cuit_cuil_cdi",
            unique=true,
            nullable=false)
    public Serializable getCuitCuilCdi() {
        return this.cuitCuilCdi;
    }

    public void setCuitCuilCdi(Serializable cuitCuilCdi) {
        this.cuitCuilCdi = cuitCuilCdi;
    }

    @Column(name="usr_create",
            nullable=false)
    public String getUsrCreate() {
        return this.usrCreate;
    }

    public void setUsrCreate(String usrCreate) {
        this.usrCreate = usrCreate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="time_create",
            nullable=false,
            length=29)
    public Date getTimeCreate() {
        return this.timeCreate;
    }

    public void setTimeCreate(Date timeCreate) {
        this.timeCreate = timeCreate;
    }

    @Column(name="usr_last_update",
            nullable=false)
    public String getUsrLastUpdate() {
        return this.usrLastUpdate;
    }

    public void setUsrLastUpdate(String usrLastUpdate) {
        this.usrLastUpdate = usrLastUpdate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="time_last_update",
            nullable=false,
            length=29)
    public Date getTimeLastUpdate() {
        return this.timeLastUpdate;
    }

    public void setTimeLastUpdate(Date timeLastUpdate) {
        this.timeLastUpdate = timeLastUpdate;
    }

    @OneToOne(fetch=FetchType.LAZY,
            mappedBy="persona")
    public PersonaJuridica getPersonaJuridica() {
        return this.personaJuridica;
    }

    public void setPersonaJuridica(PersonaJuridica personaJuridica) {
        this.personaJuridica = personaJuridica;
    }

    @OneToOne(fetch=FetchType.LAZY,
            mappedBy="persona")
    public PersonaHumana getPersonaHumana() {
        return this.personaHumana;
    }

    public void setPersonaHumana(PersonaHumana personaHumana) {
        this.personaHumana = personaHumana;
    }

    @OneToMany(fetch=FetchType.LAZY,
            mappedBy="persona")
    public List<Contacto> getContactos() {
        return this.contactos;
    }

    public void setContactos(List<Contacto> contactos) {
        this.contactos = contactos;
    }
}