package org.socialweb.model;

import java.util.Date;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Provincia generated by hbm2java
 */
@Entity
@Table(name="provincia"
    ,schema="public"
)
public class Provincia implements java.io.Serializable {

     private int codigo;
     private EstadoProvincia estadoProvincia;
     private Pais pais;
     private String nombre;
     private String codigoIso;
     private String usrCreate;
     private Date timeCreate;
     private String usrLastUpdate;
     private Date timeLastUpdate;
     private List<Ciudad> ciudades = new ArrayList<Ciudad>(0);

    public Provincia() {}

    public Provincia(int codigo,
            EstadoProvincia estadoProvincia,
            Pais pais,
            String nombre,
            String codigoIso,
            String usrCreate,
            Date timeCreate,
            String usrLastUpdate,
            Date timeLastUpdate) {

        this.codigo = codigo;
        this.estadoProvincia = estadoProvincia;
        this.pais = pais;
        this.nombre = nombre;
        this.codigoIso = codigoIso;
        this.usrCreate = usrCreate;
        this.timeCreate = timeCreate;
        this.usrLastUpdate = usrLastUpdate;
        this.timeLastUpdate = timeLastUpdate;
    }

    public Provincia(int codigo,
            EstadoProvincia estadoProvincia,
            Pais pais,
            String nombre,
            String codigoIso,
            String usrCreate,
            Date timeCreate,
            String usrLastUpdate,
            Date timeLastUpdate,
            List<Ciudad> ciudades) {

        this.codigo = codigo;
        this.estadoProvincia = estadoProvincia;
        this.pais = pais;
        this.nombre = nombre;
        this.codigoIso = codigoIso;
        this.usrCreate = usrCreate;
        this.timeCreate = timeCreate;
        this.usrLastUpdate = usrLastUpdate;
        this.timeLastUpdate = timeLastUpdate;
        this.ciudades = ciudades;
    }

    @Id
    @SequenceGenerator(name="provinciaGenerator",
            sequenceName="seq_codigo_provincia")
    @GeneratedValue(strategy=GenerationType.SEQUENCE,
            generator="provinciaGenerator")
    @Column(name="codigo",
            unique=true,
            nullable=false)
    public int getCodigo() {
        return this.codigo;
    }

    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="estado",
            nullable=false,
            insertable=false,
            updatable=false)
    public EstadoProvincia getEstadoProvincia() {
        return this.estadoProvincia;
    }

    public void setEstadoProvincia(EstadoProvincia estadoProvincia) {
        this.estadoProvincia = estadoProvincia;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pais",
            nullable=false,
            insertable=false,
            updatable=false)
    public Pais getPais() {
        return this.pais;
    }

    public void setPais(Pais pais) {
        this.pais = pais;
    }

    @Column(name="nombre",
            nullable=false)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name="codigo_iso",
            nullable=false)
    public String getCodigoIso() {
        return this.codigoIso;
    }

    public void setCodigoIso(String codigoIso) {
        this.codigoIso = codigoIso;
    }

    @Column(name="usr_create",
            nullable=false)
    public String getUsrCreate() {
        return this.usrCreate;
    }

    public void setUsrCreate(String usrCreate) {
        this.usrCreate = usrCreate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="time_create",
            nullable=false,
            length=29)
    public Date getTimeCreate() {
        return this.timeCreate;
    }

    public void setTimeCreate(Date timeCreate) {
        this.timeCreate = timeCreate;
    }

    @Column(name="usr_last_update",
            nullable=false)
    public String getUsrLastUpdate() {
        return this.usrLastUpdate;
    }

    public void setUsrLastUpdate(String usrLastUpdate) {
        this.usrLastUpdate = usrLastUpdate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="time_last_update",
            nullable=false,
            length=29)
    public Date getTimeLastUpdate() {
        return this.timeLastUpdate;
    }

    public void setTimeLastUpdate(Date timeLastUpdate) {
        this.timeLastUpdate = timeLastUpdate;
    }

    @OneToMany(fetch=FetchType.LAZY,
            mappedBy="provincia")
    public List<Ciudad> getCiudades() {
        return this.ciudades;
    }

    public void setCiudades(List<Ciudad> ciudades) {
        this.ciudades = ciudades;
    }
}