package org.socialweb.model;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoContacto generated by hbm2java
 */
@Entity
@Table(name="tipo_contacto"
    ,schema="public"
)
public class TipoContacto implements java.io.Serializable {

    private int codigo;
    private String descripcion;
    private List<Contacto> contactos = new ArrayList<Contacto>(0);

    public TipoContacto() {}

    public TipoContacto(int codigo,
            String descripcion) {

        this.codigo = codigo;
        this.descripcion = descripcion;
    }

    public TipoContacto(int codigo,
            String descripcion,
            List<Contacto> contactos) {
        this.codigo = codigo;
        this.descripcion = descripcion;
        this.contactos = contactos;
    }

    @Id
    @Column(name="codigo",
            unique=true,
            nullable=false)
    public int getCodigo() {
        return this.codigo;
    }

    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    @Column(name="descripcion",
            nullable=false)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @OneToMany(fetch=FetchType.LAZY,
            mappedBy="tipoContacto")
    public List<Contacto> getContactos() {
        return this.contactos;
    }

    public void setContactos(List<Contacto> contactos) {
        this.contactos = contactos;
    }
}