package org.socialweb.model;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoDocumento generated by hbm2java
 */
@Entity
@Table(name="tipo_documento"
    ,schema="public"
)
public class TipoDocumento implements java.io.Serializable {

    private int codigo;
    private String descripcion;
    private String descripcionCorta;
    private List<PersonaHumana> personasHumanas = new ArrayList<PersonaHumana>(0);

    public TipoDocumento() {}

    public TipoDocumento(int codigo,
            String descripcion,
            String descripcionCorta) {

        this.codigo = codigo;
        this.descripcion = descripcion;
        this.descripcionCorta = descripcionCorta;
    }

    public TipoDocumento(int codigo,
            String descripcion,
            String descripcionCorta,
            List<PersonaHumana> personasHumanas) {

        this.codigo = codigo;
        this.descripcion = descripcion;
        this.descripcionCorta = descripcionCorta;
        this.personasHumanas = personasHumanas;
    }

    @Id
    @Column(name="codigo",
            unique=true,
            nullable=false)
    public int getCodigo() {
        return this.codigo;
    }

    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    @Column(name="descripcion",
            nullable=false)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Column(name="descripcion_corta",
            nullable=false)
    public String getDescripcionCorta() {
        return this.descripcionCorta;
    }

    public void setDescripcionCorta(String descripcionCorta) {
        this.descripcionCorta = descripcionCorta;
    }

    @OneToMany(fetch=FetchType.LAZY,
            mappedBy="personasHumanas")
    public List<PersonaHumana> getPersonasHumanas() {
        return this.personasHumanas;
    }

    public void setPersonasHumanas(List<PersonaHumana> personasHumanas) {
        this.personasHumanas = personasHumanas;
    }
}